const associationMetaTags = [
  'Harcèlement',
  'Victime',
  'Agressivité',
  'Intimidation',
  'Cyberintimidation',
  'Isolement',
  'Peur',
  'Stigmatisation',
  'Maltraitance',
  'Exclusion',
  'Brimades',
  'Humiliation',
  'Manipulation',
  'Menace',
  'Dévalorisation',
  'Violence',
  'Dépression',
  'Anxiété',
  'Suicide',
  'Psychologique',
  'Physique',
  'Verbal',
  'Émotionnel',
  'Soutien',
  'Prévention',
  'Éducation',
  'Tolérance zero',
  'Écoute',
  'Respect',
  'Solidarité',
  'Conseiller',
  'Intervention',
  'Ressources',
  'Accompagnement',
  'Sensibilisation',
];

export default associationMetaTags;
